# Generated by Django 5.0.2 on 2024-02-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('token', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
