# Generated by Django 3.2 on 2024-06-22 19:25

from django.db import migrations, models
import django.db.models.deletion
import levels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('age_min', models.IntegerField(validators=[levels.models.validate_age_limit])),
                ('age_max', models.IntegerField(validators=[levels.models.validate_age_limit])),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subCategory', to='levels.trainingmaincategory')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('voice', models.URLField(max_length=500)),
                ('video', models.URLField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='levels.trainingsubcategory')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='levels.level')),
            ],
        ),
    ]
