# Generated by Django 5.0.6 on 2024-08-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='levels.trainingmaincategory'),
        ),
        migrations.AddField(
            model_name='level',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='TrainingSubCategory',
        ),
    ]
