# Generated by Django 5.0.6 on 2024-08-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_parent_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='surname',
        ),
    ]
